# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /about
    weight: 20
  - name: Documentation
    url: docs/
    weight: 30
  - name: Blog
    url: blog/
    weight: 40
  - name: Showcase
    url: showcase/
    weight: 50
  - name: Community
    url: community/
    weight: 60
  - name: Contact
    url: contact
    weight: 60

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs ↗"
    url: "https://docs.hugoblox.com"
    weight: 3
